-- CardDemo modernized batch — PostgreSQL schema.
-- Derived from the COBOL copybooks in app/cpy/. Money fields use NUMERIC(14,2) to
-- preserve the exact PIC S9(n)V99 semantics; interest rates NUMERIC(6,2) for S9(04)V99.
-- This DDL matches the SQLAlchemy models in src/carddemo_batch/models.py.

-- Card / account cross-reference (CVACT03Y CARD-XREF-RECORD)
CREATE TABLE IF NOT EXISTS card_xref (
    card_num  VARCHAR(16) PRIMARY KEY,
    cust_id   INTEGER NOT NULL,
    acct_id   INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_card_xref_acct_id ON card_xref (acct_id);

-- Account master (CVACT01Y ACCOUNT-RECORD)
CREATE TABLE IF NOT EXISTS account (
    id                 INTEGER PRIMARY KEY,
    active_status      VARCHAR(1)   DEFAULT 'Y',
    curr_bal           NUMERIC(14,2) DEFAULT 0,
    credit_limit       NUMERIC(14,2) DEFAULT 0,
    cash_credit_limit  NUMERIC(14,2) DEFAULT 0,
    open_date          VARCHAR(10)  DEFAULT '',
    expiration_date    VARCHAR(10)  DEFAULT '',   -- maps to COBOL ACCT-EXPIRAION-DATE (sic)
    reissue_date       VARCHAR(10)  DEFAULT '',
    curr_cyc_credit    NUMERIC(14,2) DEFAULT 0,
    curr_cyc_debit     NUMERIC(14,2) DEFAULT 0,
    addr_zip           VARCHAR(10)  DEFAULT '',
    group_id           VARCHAR(10)  DEFAULT ''
);

-- Customer master (CVCUS01Y / CUSTREC CUSTOMER-RECORD)
CREATE TABLE IF NOT EXISTS customer (
    id                 INTEGER PRIMARY KEY,
    first_name         VARCHAR(25) DEFAULT '',
    middle_name        VARCHAR(25) DEFAULT '',
    last_name          VARCHAR(25) DEFAULT '',
    addr_line_1        VARCHAR(50) DEFAULT '',
    addr_line_2        VARCHAR(50) DEFAULT '',
    addr_line_3        VARCHAR(50) DEFAULT '',
    addr_state_cd      VARCHAR(2)  DEFAULT '',
    addr_country_cd    VARCHAR(3)  DEFAULT '',
    addr_zip           VARCHAR(10) DEFAULT '',
    fico_credit_score  INTEGER     DEFAULT 0
);

-- Disclosure group / interest rates (CVTRA02Y DIS-GROUP-RECORD)
CREATE TABLE IF NOT EXISTS disclosure_group (
    group_id  VARCHAR(10),
    type_cd   VARCHAR(2),
    cat_cd    INTEGER,
    int_rate  NUMERIC(6,2) DEFAULT 0,
    PRIMARY KEY (group_id, type_cd, cat_cd)
);

-- Transaction category balances (CVTRA01Y TRAN-CAT-BAL-RECORD)
CREATE TABLE IF NOT EXISTS tran_cat_balance (
    acct_id  INTEGER,
    type_cd  VARCHAR(2),
    cat_cd   INTEGER,
    balance  NUMERIC(14,2) DEFAULT 0,
    PRIMARY KEY (acct_id, type_cd, cat_cd)
);

-- Transaction type descriptions (CVTRA03Y TRAN-TYPE-RECORD)
CREATE TABLE IF NOT EXISTS transaction_type (
    type_cd      VARCHAR(2) PRIMARY KEY,
    description  VARCHAR(50) DEFAULT ''
);

-- Transaction category type descriptions (CVTRA04Y TRAN-CAT-RECORD)
CREATE TABLE IF NOT EXISTS transaction_category_type (
    type_cd      VARCHAR(2),
    cat_cd       INTEGER,
    description  VARCHAR(50) DEFAULT '',
    PRIMARY KEY (type_cd, cat_cd)
);

-- Daily transaction staging (CVTRA06Y DALYTRAN-RECORD) — POSTTRAN input.
-- seq preserves the sequential file order the COBOL reads records in.
CREATE TABLE IF NOT EXISTS daily_transaction (
    seq            SERIAL PRIMARY KEY,
    id             VARCHAR(16) DEFAULT '',
    type_cd        VARCHAR(2)  DEFAULT '',
    cat_cd         INTEGER     DEFAULT 0,
    source         VARCHAR(10) DEFAULT '',
    description    VARCHAR(100) DEFAULT '',
    amount         NUMERIC(14,2) DEFAULT 0,
    merchant_id    INTEGER      DEFAULT 0,
    merchant_name  VARCHAR(50)  DEFAULT '',
    merchant_city  VARCHAR(50)  DEFAULT '',
    merchant_zip   VARCHAR(10)  DEFAULT '',
    card_num       VARCHAR(16)  DEFAULT '',
    orig_ts        VARCHAR(26)  DEFAULT '',
    proc_ts        VARCHAR(26)  DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_daily_transaction_id ON daily_transaction (id);

-- Posted transaction master (CVTRA05Y TRAN-RECORD)
CREATE TABLE IF NOT EXISTS transaction (
    id             VARCHAR(16) PRIMARY KEY,
    type_cd        VARCHAR(2)  DEFAULT '',
    cat_cd         INTEGER     DEFAULT 0,
    source         VARCHAR(10) DEFAULT '',
    description    VARCHAR(100) DEFAULT '',
    amount         NUMERIC(14,2) DEFAULT 0,
    merchant_id    INTEGER      DEFAULT 0,
    merchant_name  VARCHAR(50)  DEFAULT '',
    merchant_city  VARCHAR(50)  DEFAULT '',
    merchant_zip   VARCHAR(10)  DEFAULT '',
    card_num       VARCHAR(16)  DEFAULT '',
    orig_ts        VARCHAR(26)  DEFAULT '',
    proc_ts        VARCHAR(26)  DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_transaction_card_num ON transaction (card_num);

-- Interest transactions generated by INTCALC (SYSTRAN) before COMBTRAN
CREATE TABLE IF NOT EXISTS system_transaction (
    id             VARCHAR(16) PRIMARY KEY,
    type_cd        VARCHAR(2)  DEFAULT '',
    cat_cd         INTEGER     DEFAULT 0,
    source         VARCHAR(10) DEFAULT '',
    description    VARCHAR(100) DEFAULT '',
    amount         NUMERIC(14,2) DEFAULT 0,
    merchant_id    INTEGER      DEFAULT 0,
    merchant_name  VARCHAR(50)  DEFAULT '',
    merchant_city  VARCHAR(50)  DEFAULT '',
    merchant_zip   VARCHAR(10)  DEFAULT '',
    card_num       VARCHAR(16)  DEFAULT '',
    orig_ts        VARCHAR(26)  DEFAULT '',
    proc_ts        VARCHAR(26)  DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_system_transaction_card_num ON system_transaction (card_num);

-- Rejected daily transactions (DALYREJS) with the 80-byte validation trailer
CREATE TABLE IF NOT EXISTS daily_reject (
    id           SERIAL PRIMARY KEY,
    tran_id      VARCHAR(16) DEFAULT '',
    reason_code  INTEGER     DEFAULT 0,
    reason_desc  VARCHAR(76) DEFAULT '',
    raw_record   VARCHAR(430) DEFAULT ''
);

-- Generated statements (CREASTMT text + HTML per account)
CREATE TABLE IF NOT EXISTS statement (
    acct_id    INTEGER PRIMARY KEY,
    card_num   VARCHAR(16) DEFAULT '',
    text_body  TEXT DEFAULT '',
    html_body  TEXT DEFAULT ''
);

-- Rendered transaction report (TRANREPT)
CREATE TABLE IF NOT EXISTS transaction_report (
    id          SERIAL PRIMARY KEY,
    start_date  VARCHAR(10) DEFAULT '',
    end_date    VARCHAR(10) DEFAULT '',
    body        TEXT DEFAULT ''
);
